# Generated by Django 4.2.19 on 2025-02-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_profile_picture_user_verifierid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(default='skip', max_length=500),
            preserve_default=False,
        ),
    ]
