# Generated by Django 4.2.18 on 2025-02-19 12:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileEncryptModel',
            fields=[
                ('file_id', models.CharField(default=uuid.UUID('fab12b8b-3979-4517-bdfa-86fc45ca60da'), max_length=70, primary_key=True, serialize=False)),
                ('encryption_key', models.CharField(max_length=50)),
                ('file_url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
