# Generated by Django 4.2.18 on 2025-02-19 12:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file_encryptor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileencryptmodel',
            name='file_extension',
            field=models.CharField(default='pdf', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileencryptmodel',
            name='file_id',
            field=models.CharField(default=uuid.UUID('a9ca4835-c708-4c75-8b72-3df5b3235aeb'), max_length=70, primary_key=True, serialize=False),
        ),
    ]
