# Generated by Django 4.2.18 on 2025-02-19 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file_encryptor', '0002_fileencryptmodel_file_extension_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileencryptmodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='fileencryptmodel',
            name='encryption_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fileencryptmodel',
            name='file_id',
            field=models.CharField(default=uuid.UUID('2f14ee8b-76b6-44aa-9718-20bf4e7eda08'), max_length=70, primary_key=True, serialize=False),
        ),
    ]
