# Generated by Django 4.2.18 on 2025-02-19 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file_encryptor', '0003_remove_fileencryptmodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileencryptmodel',
            name='file_id',
            field=models.CharField(default=uuid.UUID('a4e6601a-4119-40d9-8186-9142884be98d'), max_length=70, primary_key=True, serialize=False),
        ),
    ]
