# Generated by Django 4.2.18 on 2025-02-19 13:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('file_encryptor', '0004_alter_fileencryptmodel_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileencryptmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileencryptmodel',
            name='file_id',
            field=models.CharField(default=uuid.UUID('81a753e8-960b-4239-a3ed-dde77f1b5aee'), max_length=70, primary_key=True, serialize=False),
        ),
    ]
