# Generated by Django 4.2.19 on 2025-02-24 10:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file_encryptor', '0005_fileencryptmodel_user_alter_fileencryptmodel_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileencryptmodel',
            name='file_id',
            field=models.CharField(default=uuid.UUID('34af5571-467a-4a77-b4d0-8baaef281231'), max_length=70, primary_key=True, serialize=False),
        ),
    ]
