# Generated by Django 4.2.19 on 2025-02-24 11:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file_encryptor', '0006_alter_fileencryptmodel_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileencryptmodel',
            name='file_id',
            field=models.CharField(default=uuid.UUID('cfd12735-45be-451b-8e01-4944a4f6c8da'), max_length=70, primary_key=True, serialize=False),
        ),
    ]
