# Generated by Django 4.2.19 on 2025-02-26 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file_encryptor', '0007_alter_fileencryptmodel_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileencryptmodel',
            name='file_id',
            field=models.CharField(default=uuid.UUID('93315314-b27d-4533-9335-f2502a30409d'), max_length=70, primary_key=True, serialize=False),
        ),
    ]
