# Generated by Django 4.2.19 on 2025-02-26 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file_encryptor', '0008_alter_fileencryptmodel_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileencryptmodel',
            name='file_id',
            field=models.CharField(default=uuid.UUID('5a6ecdac-0448-4482-bdda-874a96efea43'), max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
