# Generated by Django 4.2.19 on 2025-02-26 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file_encryptor', '0009_alter_fileencryptmodel_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileencryptmodel',
            name='file_id',
            field=models.CharField(default=uuid.uuid4, max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
