# Generated by Django 4.2.19 on 2025-03-05 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file_encryptor', '0010_alter_fileencryptmodel_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileencryptmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileencryptmodel',
            name='file_name',
            field=models.CharField(default='2025-03-05 12:56:19.586116', max_length=150),
            preserve_default=False,
        ),
    ]
