# Generated by Django 4.2.19 on 2025-04-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_encryptor', '0011_fileencryptmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileencryptmodel',
            name='google_drive_file_id',
            field=models.CharField(default='<function uuid4 at 0x000001CD0BDA0160>', max_length=200),
        ),
        migrations.AlterField(
            model_name='fileencryptmodel',
            name='file_id',
            field=models.CharField(default='2025-04-03T11:18:39.429047-<function uuid4 at 0x000001CD0BDA0160>', max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
